language: python
python: 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
# this tests to make sure that it builds properly
- make doctest
- make coverage
- make html

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build/html
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
