language: python
python: 3.6
cache: pip
addons:
  apt:
    packages:
      - mpv
      - libmpv-dev
      - youtube-dl
install:
  - pip install --upgrade pip
  - pip install .
script:
  - make doctest
  - make coverage
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build/html
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
