sudo: required

language: python

services:
  - docker

before_install:
  - docker pull

install:
  - pip install --upgrade pip
  - pip install .
script:
  # Render the diagrams
  - pushd docs/diagrams
  - make
  - popd

  # Make the Sphinx documentation
  - make doctest
  - make coverage
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build/html
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
