######################################################################
# Automatically generated by qmake (3.1) Tue Apr 3 19:09:49 2018
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += build-visplay-gui-Qt_5_9_4_System-Debug.pro
