[package]
name = "visplay-host"
version = "0.1.0"
authors = ["Sam Sartor <me@samsartor.com>"]

[dependencies]
clap = "*"
protobuf = "*"
log = "*"
simplelog = "*"
zombie = "0.0.4"
x11-dl = "*"
libc = "*"
lazy_static = "*"